

def random_title(index=False):
    quotes = [
        'let everything happen to you', 'beauty and terror', 'no feeling is final', 'just keep going', 'all is folly except the sky', 'less is more', 'except the sky', 'elegance is elimination', 'midnight moves over metropolis', 'rise', 'they are of the world', 'greater is he', 'remember', 'malice', 'hide behind the money', 'accept everything', 'look inwards', 'love|obsession', 'the fire rises', 'fashion fades|beauty is eternal', 'my name is legion', 'villain|flux', 'life is self-deception', 'odyssey of dark roads', 'form follows function', 'the night is deception', 'its graceless being a martyr', 'the self at dusk', 'here for the moment', 'my disease happens to be the ideal', 'my tragedy my masterpiece', 'americas tortured brow', 'writ large in lifes libretto', 'they had something she lacked', 'the sould discharges it passions on false objects when the true ones fail it', 'learn to die', 'tragedy is upon you', 'boredem>begging>forgotten', 'then and thereafter', '6 shots', 'INT. CASH, DAY', 'style and substance', 'righteous destiny', 'hang up and try again', 'night addict', 'metropolis park', 'we are not the same', 'baby carriage for sale. unused', 'take me to your skinner box', 'celluloid dreams', 'bad city, somewhere', 'murder she spoke', 'double indemnity', 'rhythms resemble home', 'bad things happen', 'life is folly|signifying nothing', 'south of heaven', 'east of eden', 'live means die', 'bored by the 2nd bomb', 'kiss kiss bang bang', 'changing planes in paris', 'some like it hot', 'sparkle motion', 'au revoir', 'are you the devil', 'once upon a time in delusion', 'the sin of man', 'rebirth requires death', 'love is eastside', 'order tends to disorder', 'its alive', 'shes a monster', 'make them remember', 'remember what they took', 'thanks to the lord in advance', 'live in silence', 'dont make trouble for humans', 'exist in silence', 'dont take advice', 'the end of the fu***** world', 'sinister lone rider', 'slightly funny ridiculously twisted', 'silence beckons', 'shockingly indifferent', 'masked spider troupe', 'picture of a man staring at a picture', 'the shows over', 'welcome to me', 'halway to hell', 'fluoride dreams', 'stop thinking', 'let my pipe bang', 'alice in the wall', 'myself', 'andrew bolkonski', 'i dont exist', 'cathy ames', 'the wolf waits', 'depths of the unconscious', 'forget it jake', 'terror is glory', 'man is wolf to man', 'honor no kings|reject the trinity', 'they are overrated', 'dashed hopes|good intentions', 'half my attention', 'youre still here?', 'crash like thunder', 'might as well live', 'learn all things', 'knowledge is purpose', 'flux', 'villain', 'devil', 'no warranty in mortals', 'judge them', 'morality is performance', 'is=/=ought', 'dont beleive their performance', 'character is destiny', 'action is character', 'character is action', 'excitement is not happiness', 'a crowd is untruth', 'perspective is destination', 'gap between stimulus & response', 'suffering is opportunity', 'offer no resistance', 'success should surprise you', 'accept what you cant change', 'things are not what they seem', 'you are your only obstacle', 'begin with doubts|end in certainties', 'KFKD', 'starve yourself of your thoughts', 'thinking|rearranging prejudices', 'follow fear', 'fear is glory', 'reasonable men adapt themselves', 'rock bottom is a solid foundation', 'the abyss stares back', 'sit in judgment of self|others', 'worst memories|biggest illusions', '12 glib little reasons', 'find the extent of your ignorance', 'nothing is what it seems', 'life is a game', 'knowledge is the liberator', 'suffer|create', 'creation is redemption', 'steal victory by laughing at defeat', 'no one is looking for you', 'man never steps in the same river twice', 'homo homini lupus', 'man|wolf|man', 'everything is only for a day', 'sleep is death', 'if its a story|theres an audience', 'what what a boy know of destiny', 'separation is illusion', 'they believe they are what they pretend to be', 'make the darkness conscious', 'man vs power|memory vs forgetting', 'a cold winters day', 'afraid to be seen failing', 'lifes a walking shadow', 'full of sound and fury|signifying nothing', 'learn no names'
        "Its like in the great stories Mr",
        "The ones that rea lly mattered",
        "of darkness and danger they were",
        "etimes you didnt want to know the",
        "Because how could th e end be",
        "How could the world go back to the way",
        "s when so much bad had happened",
        "the end its only a passing",
        "Even darkness must pass  A",
        "And when the sun",
        "it will shine out the clearer",
        "the stories that stayed with you",
        "something even if you were",
        "to understand wh y",
        "Frodo I do understand",
        "in those stories had lots of chances",
        "turning back only they didnt",
        "going because they were holding on",
        "That there is some good",
        "Our deepest fear is not that we",
        "Our deepest fear is that",
        "are powerful beyond measure",
        "not our darkness that most",
        "We ask ourselves who am I to be",
        "gorgeous talented and",
        "Actually who are you not to be",
        "are a child of God",
        "not serve the world",
        "enlightened about shrinking so that",
        "people wont feel insecure around",
        "Its not just in some of us its in",
        "And as we let our own light",
        "we unconsciously give other",
        "to do the same",
        "If only it were all so simple",
        "there were evil people somewhere",
        "committing evil deeds and it",
        "necessary o nly to separate them",
        "rest of us and destroy them",
        "it was disclosed to me that the",
        "separating good and evil passes not",
        "stat es nor between classes nor",
        "political parties either-but right",
        "every human heart",
        "of any heart this line keeps changing",
        "sometimes it is squeezed one way by",
        "uberant evil and sometimes it shifts",
        "allow enough space for good to flourish",
        "One and the same human being is at",
        "ages under various circumstances",
        "different human being at",
        "The good and evil resulting from",
        "words and deeds go on apportioning",
        "one assumes in a reasonably",
        "and balanced way throughout all the",
        "to follow including those endless",
        "s when we shall not be here to nd",
        "congratulate ourselves or ask for",
        "indeed there are those who claim",
        "the truth is that the",
        "in which the rulers are most reluctant",
        "govern is always the best and most",
        "You are young my son",
        "and even reverse many of your",
        "Refrain therefore",
        "Alas Why does man boast of",
        "superior to those apparent in the",
        "Guns are unlawful nooses give",
        "If you are willing to look at",
        "persons behavior toward you as a",
        "of their relation ship with",
        "rather than a statement about your",
        "He who is not contended with what",
        "You must learn all things both",
        "heart of well-rounded truth",
        "It is the mark of an educated",
        "Many people think excitement is",
        "But when you are excited you",
        "In the universe all things are",
        "For him who can but realize his",
        "unity with the whole the parts",
        "body mean no mo re than so much",
        "dirt and death and life end and",
        "are no more to him than the su",
        "When you see a man casting pearls",
        "getting even a pork chop in",
        "is not against the swine that you",
        "It is against the man",
        "his pearls so little that he was",
        "to fling them into the mu ck",
        "We are not enemies but friends",
        "We must not be enemies",
        "have strained it must not break our",
        "The mystic chords of",
        "will swell when again touched as",
        "It did not really matter what we",
        "from life but rather what life",
        "We needed to stop asking",
        "the meaning of life and instead to",
        "of ourselves as those who were",
        "questioned by life -- daily and hourly",
        "Our answer must consist not in talk",
        "but in right action and in",
        "Life ultimately means",
        "the responsibility to nd the right",
        "to its problems and to ful ll the",
        "Perhaps the most valuable result",
        "education is the ability to make",
        "do the thing you h ave to do",
        "ought to be done whether you like it",
        "not it is the rst lesson that ought",
        "be learned and however early a mans",
        "begins it is probably the last",
        "Only a brain that is functioning",
        "is characterized by the",
        "Suffering presents us with a",
        "to nd our goals and purpose in our",
        "Between stimulus and response",
        "In that space is our",
        "To offer no resistance to life is",
        "be in a state of grace ease and",
        "This state is no longer",
        "things being in a certain way good",
        "All those things of course",
        "pass away cycles will come and",
        "Among men who rise to fame and",
        "two types are recognizable--those",
        "are born with a beli ef in",
        "those in whom it is a slow growth",
        "on actual achievement",
        "the last type their own success is a",
        "surprise and its fruits the",
        "ious yet to be tested",
        "a haunting sense of doubt whether",
        "In that doubt lies",
        "modesty not the sham of insincere",
        "but the modesty of mod",
        "Whoever wishes to be free should",
        "seek nor avoid anything that is up",
        "others otherwise he will",
        "Remember that it is not",
        "who curses you or hits you that",
        "you but the idea you have of them",
        "If someone were to hand",
        "your body to just whomever happened",
        "you would be outraged",
        "at the fact you turnover your",
        "to whomever happens along--if he",
        "The only thing that stands",
        "man and what he wants from life is",
        "the will to tr y it and the",
        "to believe that it is possible",
        "Vladimir Nabokov I have never been",
        "in what is called the",
        "social comment (in journalistic an",
        "parlance great books)",
        "sincere I am not provocative I am",
        "satirical",
        "and so on leave me completely",
        "For me a work of ction",
        "insofar as it affords me what I",
        "bluntly call aesthetic bliss that",
        "sense of being so mehow somewhere",
        "with other states of being where",
        "- curiosity tenderness kindness e",
        "There are not",
        "All the rest are topical",
        "or what some might call the",
        "Common sense is the most fairly",
        "thing in the world for each",
        "he is so well-e ndowed with it",
        "even those who are hardest to satisfy",
        "all other matters are not in the",
        "If a man will begin with",
        "he shall end in doubts",
        "If you are not careful station",
        "D will play in your head 24 hours a day",
        "Out of the right",
        "in your inner ear will come the",
        "stream of self-aggrandizement the",
        "of ones specialness of how",
        "open and gifted and brilliant and",
        "and mis understood and humble one",
        "Out of the left speaker will be the",
        "songs of self-loathing the lists of",
        "the things one doe snt do well of",
        "the mistakes one has made today and",
        "entire lifetime the doubt the",
        "that everything that one touches",
        "to shit that one doesnt do",
        "well that o ne is in every way a",
        "incapable of selfless love that",
        "People who are feasting on their",
        "thoughts instead of nding out how",
        "they desire migh t actually come",
        "pass that over so as to avoid",
        "about whats possible",
        "assume that what they desire is",
        "and proceed to arrange the rest",
        "in thinking through",
        "theyll do when they have what they",
        "For such is the nature of men",
        "they may acknowledge many",
        "to be more witty or more eloquent",
        "learned yet they will hardly",
        "there be many so wise as themselves",
        "To prejudge other mens notions",
        "we have looked into them is not to",
        "their darkness but to put out our",
        "Hunting after arguments to make",
        "one side of a question and wholly to",
        "those which favor the other is",
        "We must know truth and we must",
        "error these are our rst and great",
        "as would-be knowers but",
        "not two ways of stating the same",
        "they are two separable laws",
        "regard the chase for truth as",
        "and avoidance of error as secondary",
        "may on the other hand treat",
        "of error as more imperative and",
        "take its chance",
        "go without belief forever than",
        "lie merely shows his own",
        "of becoming a dupe",
        "of many of his desires and fears",
        "this fear he slavishly obeys",
        "imagine anyone questions its blinding",
        "In a world where we are so",
        "incur errors in spite of all out",
        "a certain lightness of heart seems",
        "than this excessive nervousness",
        "The question of having",
        "beliefs at all or not having them",
        "Are our moral",
        "true or false or are they only",
        "phenomena making things g",
        "or bad for us but in themselves",
        "If your heart does not want a",
        "moral reali ty your head will",
        "never make you believe in one",
        "many people think they are thinking",
        "I had become strenged in mind and",
        "reached the summit of life from which",
        "lay all before me  standing as a",
        "fool on the summit and seeing",
        "there was nothing in life and ne",
        "would be",
        "only so long as he was drunk but",
        "he sobered up he could not help",
        "that all was only deception and",
        "deception at that",
        "is the direct and immediate object",
        "our existence must entirely fail",
        "It is absurd to look upon",
        "amount of pain that abounds",
        "in the world and orig inates in",
        "and necessities inseparable from",
        "as serving no purpose at all",
        "r est of mere chance",
        "misfortune as it comes seems no",
        "to be something exceptional but",
        "in general is the rule",
        "in being vitally concerned with",
        "ultimate reality to which I give the",
        "na me of God",
        "on the meaning of life is on",
        "verge of an act of faith Almost all",
        "of meaning in life really seem to",
        "only the idea that life has a",
        "ic kind of meaning one determined",
        "agents purposes or principle somehow",
        "to this worl d",
        "the conclusion that life has no",
        "Their pronouncement that",
        "The reasonable man adapts himself",
        "the world the unreasonable one",
        "adapt the world to himself",
        "Im motivated by fear",
        "being scared to do something",
        "attacking things that I was scared",
        "Fear is in our interpretations",
        "a product of our imagination causing",
        "fear things that do not at present",
        "Do not give fear a vote -- look it",
        "the face and say this is not a",
        "God placed the best things in live",
        "other side of terror on the other",
        "An optimist sees an opportunity",
        "Had I really succeeded at",
        "I might never have found the",
        "to succeed in th e one arena",
        "I believe I truly belonged",
        "How many of us I wonder can",
        "that childhood moment--when we",
        "happiness as a state of being",
        "moment of untarnished joy--that",
        "when everything in our world was",
        "Everything was alright",
        "become a colony of adults and",
        "Its as if were on a",
        "And yet the more we",
        "on our own personal happiness the",
        "We should concern",
        "not so much with the pursuit of",
        "This longing to commit a madness",
        "with us throughout our lives",
        "not when standing with someone by an",
        "or high up on a tower had a sudden",
        "to push the other over And how",
        "it that we hurt those we love although",
        "know that remorse will fol low Our",
        "being is nothing but a ght against",
        "forces within ourselves",
        "to war with trolls in heart and soul",
        "Every time you remember",
        "mind changes it just a little",
        "Every man always has handy a",
        "How many a dispute could have",
        "into a single paragraph if the",
        "Faith is to believe what you do",
        "rst thing youll learn is",
        "is what it seems ignore your",
        "dont trust anyt hing what you",
        "you hear what people tell you",
        "think you remember",
        "over you absorb it like a sponge",
        "nothing only can you be prepared",
        "Your body is not who",
        "are you shed it like a sleeve",
        "wake up the world will not be the",
        "and neither will you",
        "It isnt the mountains ahead to",
        "Those who approach life like a",
        "No Life has not disappointed me",
        "On the contrary from year to year I nd",
        "richer more desirable and more",
        "from the d ay on which the great",
        "broke my fetters the thought that",
        "may be an experiment of the",
        "not a duty not a fatality not a",
        "And knowledge itself may be for",
        "someth ing different for example a",
        "of ease or the path to a bed of",
        "an entertainment or a c ourse of",
        "for me it is a world of dangers and",
        "in which even the heroic",
        "have their arena and dancing floor",
        "Life as a means to knowledge with",
        "in ones heart one can not",
        "brave but can even live joyfully",
        "laugh joyfully And who could know",
        "laugh well and live well who did",
        "To speak truly few adult persons",
        "Most persons do not see",
        "At least they have a very",
        "The sun illuminates only",
        "of the man but shines into the",
        "the heart of the child",
        "is he whose inward and outward",
        "are still truly adjusted to each",
        "There is not a single true work",
        "that has not in the end added to the",
        "freedom of each p erson who has",
        "Yes that is the",
        "As a suffering creature I cannot",
        "without something greater than I --",
        "Creation-that is the great",
        "from suffering and lifes growing",
        "But that the creator may be much",
        "is needed and much change",
        "The force that through the green",
        "drives the flower",
        "If at this moment you and I and",
        "our companions were not aboard these",
        "in the midst of t he sea in this",
        "solitude in a condition as",
        "and risky as you please what other",
        "tuation in life would we nd ourselves",
        "Do you think more happily",
        "would we not rather be in some greater",
        "or anxiety or else fu ll of",
        "Even if we gain no other benet from",
        "voyage it seems to me that it is",
        "table to us in that for a while",
        "us free of boredom renders life",
        "to us and makes u s value many",
        "Even when beaten you can steal a",
        "Most of us can read the writing",
        "People are content to sit and",
        "world burn complain when the ash",
        "The righteous shall rejoice when",
        "She cannot be lost because no one",
        "No man ever steps in the same",
        "To speak impartially both",
        "very true That Man to Man is a kind",
        "God and that Man to Man is an",
        "The rst is true if we compare",
        "amongst themselves and the",
        "we compare Cities",
        "some analogie of similitude with the",
        "to wit Justice and Charity the",
        "of peace But in the other",
        "men must defend themselves by taking",
        "Everything is only for a day",
        "that which remembers and that which is",
        "Observe constantly that all",
        "take place by change and accustom",
        "to consider that the n ature of",
        "universe loves nothing so much as to",
        "things which are and to make new",
        "For everything that",
        "is in a manner the seed of that",
        "be Thou wilt die soon and thou",
        "yet simple nor free from",
        "nor without suspicion of being hurt",
        "things nor kindly disposed",
        "If its a story even in my head",
        "be telling it to someone",
        "tell a story only to yourself",
        "Are you living or are you just",
        "People who repeatedly attack your",
        "and sefl esteem are quite aware",
        "The belief that there is only one",
        "and that oneself is in possession",
        "everything happen to you",
        "Destiny What would a boy know of",
        "If a sh lives its whole life in",
        "river does he kn ow the rivers",
        "No Only that it runs on and on out",
        "He may follow where it",
        "Separation is our minds greatest",
        "Transcendence is not an",
        "but rather",
        "All things that you are you also are",
        "illusion of this world",
        "illusion of separation",
        "are separate and different are",
        "one and the same One does not",
        "by imagining gures of",
        "by making the darkness conscious",
        "Carl Jung // The rejection of the",
        "usually has unfortunate results",
        "the more negative the attitude of",
        "conscious towards the unconscious",
        "dangerous does the latter",
        "A formidable concession to the external",
        "a genuine self-sacrice which drives",
        "ego straigh t into identication",
        "persona so that people really do",
        "The struggle of man against power",
        "One cold winters day a number",
        "huddled together quite",
        "order through their mutual warmth",
        "themselves from being frozen",
        "they soon felt the effect of their",
        "on one another which made them again",
        "Now when the need for",
        "more brought them together the",
        "of the quills was repeat ed so",
        "were tossed between two evils",
        "had discovered the proper distance",
        "wh ich they could best tolerate one",
        "Thus the need for society",
        "from the emptiness and monotony",
        "lives drives them together",
        "many unpleasant and repulsive",
        "and insufferable drawbacks once more",
        "The mean distance",
        "they nally discover and which",
        "to endure being together is",
        "and good manners",
        "keep to this is told in England to",
        "By virtue thereof",
        "true that the need for mutual warmth",
        "be only imperfectly satised but",
        "other hand the prick of the quills",
        "Yet whoever has a",
        "of internal warmth of his own will",
        "to keep away from society in",
        "No people will tamely surrender",
        "Liberties nor can any be easily",
        "when knowledge is diffusd and",
        "On the Contrary when",
        "are universally ignorant and",
        "in their Manners they will si nk",
        "A popular Government without",
        "information or the means of",
        "is but a Prologue to a Farce or a",
        "or perhaps both",
        "govern ignorance And a people",
        "to be their own Governors must",
        "I consider knowledge to be the",
        "a republic and as the weak and the",
        "are generally in alliance as",
        "The philosophers have only",
        "the world in various ways the",
        "is to change-not it as Marx",
        "but ourselves",
        "the same thing There can be only",
        "permanent revolution a moral one",
        "ation of the inner man",
        "revolution to take place Nobody",
        "how it will take place in humanity",
        "ma n feels it clearly in himself",
        "And yet in our world everybody thinks",
        "The whole problem with the world",
        "fools and fanatics are always so",
        "Lifes but a walking shadow a",
        "that struts and frets his hour",
        "the stage and the n is heard no",
        "it is a tale told by an idiot full of",
        "had something she lacked",
        "didnt know what it was",
        "knew this she was ready",
        "Channeling devil is about never",
        "a single ounce of emotion",
        "interest reaction or politeness",
        "people know you are angry but only",
        "withholding--not through direct",
        "explicity gesutring",
        "source of condence",
        "trying to t in and not offende nayone",
        "gain the alppha enery that destroys",
        "Refer to the bible every time you",
        "the house and everytime you are",
        "if you believe yourself ot be the",
        "The masked spider troupe member",
        "No emotion in voice",
        "Unless suffering is the direct",
        "object of life our existence",
        "entirely fail of its aim",
        "look upon the enormous amount of pain",
        "abounds everywhere in the world and",
        "in needs and necessities",
        "from life itself as serving no",
        "at all and the result of mere chance",
        "separate misfortune as it comes",
        "no doubt to be something",
        "The most powerful tool to hurt",
        "with is indifferent isolation",
        "someone and not showing any sign that",
        "care will always be more lethal than",
        "Most people never succeed because",
        "stay in their heads replaying or",
        "corrupted scenarios",
        "life happen",
        "Backwards but it must be",
        "The only thing that stands",
        "a man and what he wants from life is",
        "Admiration and popularity among a",
        "To be well received in a",
        "degenerates is although on the",
        "Not living up to your ideal",
        "ideal student ideal successful",
        "ideal writer ideal smart person",
        "is meaningless to me because",
        "is just a regurgitated axiom you",
        "unthinkingly--from the mouth of one",
        "unoriginal person copied",
        "People who repeatedly attack your",
        "and self-esteem are quite aware",
        "potential even if youre not",
        "IPATE who they will be and what they",
        "when it comes to you",
        "is before it comes before you",
        "you will have clogged",
        "they would have otherwise had",
        "deepest parts of your unconscious",
        "existence is a challenge to all the",
        "Although their",
        "will manifest in many ways they",
        "all be the same a rebuttal to that",
        "These rebuttals are tremendously",
        "Are they not what dictates all",
        "behavior unrelated to sex and",
        "Yet the rst step to deflecting them",
        "DO NOT SUBMIT to the mundane No",
        "how many positive warm emotions are",
        "Your unconscious will",
        "and fear/anxiety and cravings",
        "and happiness and laughs and",
        "and butterflies to call to you",
        "sirens song and to pull you into the",
        "of the ordinary and unexceptional",
        "FUCK HUMANS and FUCK THE",
        "THEY THINK THEY CHOSE",
        "But you have to stay different --",
        "has to earn his prestige",
        "day of his life",
        "for what they are and forget them",
        "Dont let them live in your mind longer",
        "Thousands of years ago the rst",
        "how to make re",
        "burned at the stake he had taught",
        "He was considered",
        "who had dealt with a demon",
        "But thereafter men had re",
        "them war to cook their food to",
        "He had left them a gift",
        "had not conceived and he had lifted",
        "Centuries later",
        "rst man invented the wheel",
        "torn on the rack he had taught",
        "He was considered a",
        "who ventured into forbidden",
        "But thereafter men could",
        "He had left them a",
        "they had not conceived and he had",
        "the roads of the world",
        "unsub missive and rst stands in the",
        "chapter of every legend mankind has",
        "about its beginning",
        "chained to a rock and torn by",
        "he had stolen the re of the gods",
        "Adam was condemned to",
        "had eaten the fruit of the tree of",
        "Whatever the legend somewhere",
        "shadows of its memory mankind knew",
        "its glory began with one and that",
        "paid for his courage",
        "there were men who took rst",
        "down new roads armed with nothing but",
        "Their goals differed",
        "they all had this in common that the",
        "was rst the road new the vision",
        "and the response whey",
        "The great creatorsthe thinkers",
        "artists the scientists the",
        "alone against the men of their time",
        "Every great new thought was opposed",
        "great new invention was denounced",
        "The rst motor was considered foolish",
        "airplane was considered impossible",
        "power loom was considered vicious",
        "was considered sinful",
        "of unborrowed vision went ahead",
        "they suffered and they paid",
        "they won No creator was prompted by a",
        "to serve his brothers for his",
        "rejected the gift he offered and",
        "destroyed the slothful routine of",
        "His truth was his only",
        "His own truth and his own work to",
        "it in his own way",
        "an engine a philosophy an airplane",
        "a buildingthat was his goal and his",
        "Not those who heard read",
        "flew or inhabited the thing he",
        "The creation not its users",
        "The creation not the benets others",
        "The creation which gave",
        "He held his truth",
        "things and against all men",
        "his strength his courage came from",
        "A mans spirit",
        "That entity which is his",
        "To think to feel to",
        "creators were not selfless it",
        "whole secret of their powerthat it",
        "self-sufcient self-motivated",
        "A rst cause a fount of",
        "life force a Prime Mover",
        "nothing and no one",
        "And only by living for",
        "was he able to achieve the things",
        "are the glory of mankind",
        "of achievement",
        "except through his mind",
        "His brain is his only",
        "Animals obtain food by force",
        "no claws no fangs no horns no",
        "strength of muscle",
        "To plant he needs a",
        "To hunt he needs",
        "and to make weaponsa process of",
        "From this simplest necessity to",
        "highest religious abstraction from",
        "to the skyscraper everything we",
        "everything we have comes from a",
        "attribute of manthe function of his",
        "But the mind is an",
        "There is no such",
        "as a collective brain",
        "thing as a collective thought",
        "reached by a group of men is",
        "compromise or an average drawn upon",
        "It is a",
        "The primary act-the",
        "reasonmust be performed by each man",
        "We can divide a meal among many",
        "We cannot digest it in a collective",
        "No man can use his brain to",
        "All the functions of",
        "He is not concerned with them in",
        "Not in his aim not in",
        "motive not in his thinking not in",
        "not in the source of his energy",
        "He does not exist for any other",
        "asks no other man to exist for him",
        "This is the only form of brotherhood and",
        "respect possible between men",
        "of ability vary but the basic",
        "remains the same the degree of a",
        "initiative and personal",
        "for his work determines his talent as",
        "and his worth as a man",
        "is the only gauge of human virtue",
        "What a man is and makes of",
        "not what he has or hasnt dont for",
        "There is no substitute for",
        "There is no standard of",
        "dignity except independence",
        "relationships there is no sacrice",
        "An architect needs",
        "but he does not subordinate his",
        "They need him but",
        "do not order a house just to give him",
        "Men exchange their work",
        "mutual consent to mutual advantage",
        "their personal interest agree and",
        "desire the exchange",
        "desire it they are not forced to deal",
        "They seek further",
        "is the only possible form of",
        "Anything else is a",
        "of slave to master or victim to",
        "No work is ever done",
        "by a majority decision",
        "job is achieved under the guidance",
        "single individual thought",
        "requires a great many men to erect his",
        "But he does not ask them to",
        "They work together by",
        "agreement and each is free in his",
        "An architect uses steel",
        "concrete produced by others",
        "materials remain just so much steel",
        "and concrete until he touches them",
        "What he does with them is his individual",
        "and his individual property",
        "the only pattern for proper",
        "The rst right on earth",
        "right of the ego",
        "His moral law is never to",
        "his prime goal within the person of",
        "His moral obligation is to do",
        "wishes provided his wish does not",
        "primarily upon other men",
        "the whole sphere of his creative",
        "his thinking his work",
        "include the sphere of the gangster",
        "altruist and the dictator",
        "A man cannot rob",
        "or rulealone",
        "and ruling presuppose victims",
        "They are the",
        "the second-hander",
        "They create nothing",
        "exist entirely through the persons of",
        "Their goal is in their subjects",
        "the activity of enslaving",
        "as the beggar the social",
        "and the bandit",
        "But men were taught",
        "second-handerstyrants",
        "exponents of egotism",
        "fraud they were made to destroy the",
        "themselves and others",
        "fraud was to destroy the creators",
        "Which is a synonym",
        "From the beginning of history the two",
        "have stood face to face the",
        "and the second-hander",
        "invented the wheel the rst",
        "He invented",
        "The creatordenied opposed",
        "exploitedwent on moved forward and",
        "all humanity along on his energy",
        "The second-hander contributed nothing to",
        "process except the impediments",
        "has another  the individual",
        "The common good of a",
        "race a class a statewas",
        "and justication of every tyranny",
        "established over men",
        "of history was committed in the of",
        "Has any act of",
        "ever equaled the carnage",
        "disciples of altruism Does the fault",
        "in mens hypocrisy or in the nature",
        "principle The most dreadful",
        "They believed in",
        "society reached through the",
        "and the ring squad",
        "their right to murder since they",
        "for an altruistic purpose",
        "accepted that man must be sacriced",
        "Actors change but the",
        "of the tragedy remains the same",
        "who starts with declarations",
        "for mankind and ends with a sea of",
        "It goes on and will go on so long",
        "men believed that an action is good if",
        "That permits the",
        "act and forces his victims to bear it",
        "The leaders of collectivist movements",
        "nothing for themselves",
        "The only good which men can",
        "to one another and the only statement",
        "proper relationship is Hands",
        "Now observe the results of a society",
        "the principle of individualism",
        "The noblest country in",
        "The country of",
        "achievement greatest prosperity",
        "This country was not based",
        "selfless service sacrice",
        "any precept of altruism",
        "a mans right to the pursuit of",
        "His own happiness",
        "A private personal selsh motive",
        "Look at the results",
        "It is an ancient conflict",
        "Men have come close to the truth but",
        "was destroyed each time and one",
        "fell after another",
        "progress toward a society of privacy",
        "The savages whole existence is",
        "by the laws of his tribe",
        "is the process of setting man free",
        "Now in our age",
        "rule of the second-hander and",
        "the ancient monster has broken",
        "and is running amuck",
        "to a level of intellectual indecency",
        "It has reached a",
        "of horror without precedent",
        "It has swallowed",
        "It is engulng our",
        "I am an architect",
        "by the principle on which it is",
        "It is said that I have destroyed",
        "home of the destitute",
        "but for me the destitute could not",
        "had this particular home",
        "with the poor had to come to",
        "who have never been concerned in",
        "It is believed that",
        "of the future tenants gave them",
        "That their need",
        "a claim on my life",
        "to contribute anything demanded of me",
        "the second-handers credo now",
        "I came here to say that I",
        "recognize anyones right to one",
        "Nor to any part of my energy",
        "Nor to any achievement of mine",
        "makes the claim how large their",
        "or how great their need",
        "here and say that I am a man who does",
        "It had to be said",
        "world is perishing from an orgy of",
        "I wished to come here and say",
        "the integrity of a mans creative",
        "of greater importance than any",
        "Those of you who do not",
        "this are the men whore",
        "I wished to come here and",
        "I do not care to exist on any",
        "I recognize no obligations toward",
        "except one to respect their freedom",
        "Roark before I met you I had",
        "been afraid o seeing someone like",
        "because I knew that id also have to",
        "I saw on the witness stand and Id",
        "to do what it did in that courtroom",
        "doing it because it was insult to",
        "to defend youand it was an insult to",
        "that you had to be defended",
        "I can accept anything except what",
        "to be the easiest for most people",
        "the almost the just-about",
        "They may have their",
        "I dont care to inquire",
        "I know that it is the one thing not",
        "What I think of what",
        "are I cant accept any reality except",
        "Or at least a world",
        "which you have a ghting chance and a",
        "That does not exist",
        "IC ant live a life torn between that",
        "It would mean to",
        "against things and men who dont",
        "to be your opponents",
        "methodsand thats too horrible a",
        "It would mean doing for you",
        "I did for Peter Keating lie flatter",
        "compromise pander to every",
        "order to beg of them a chance for",
        "beg them to let you live to let you",
        "Roark not to laugh",
        "but to tremble because they hold",
        "power to hurt you",
        "I cant do this I dont know which is",
        "greater strength to accept all this",
        "to love you so much that the",
        "Do you understand this Roark",
        "not answer Toohey went on softly",
        "it look like to you Like a",
        "mess Like a chance collection of",
        "Like an imbecile mess But is it Mr",
        "Roark Do you see no method You who",
        "the language of structure and the",
        "Do you see no purpose here",
        "none in discussing it Mr",
        "Why dont you tell me",
        "think of me In any words you wish",
        "But I dont think",
        "Tooheys face had an expression",
        "of listening quietly to",
        "as simple as fate",
        "and Roark asked What did you want",
        "to me Toohey looked at him and",
        "bare trees around them at the",
        "below at the great rise of the sky",
        "average person will tend to",
        "The night was foggy and through",
        "the mmonlight gleamed mysteriously",
        "Yes tomorrow tomorrow he thought",
        "Tomrrow everything may be over for",
        "All these memories will be no more",
        "them will have any meaning for me",
        "perhaps even certainly I hjave",
        "that for the rst time I",
        "have to show all I can do",
        "pictured the battle its loss the",
        "of ghting at one point and",
        "hesitatino of all the cammanders",
        "happy moment that Toulon for",
        "had so long waited presents itself",
        "He rmly and clearly",
        "his opinion to Kutuzov to Weyrother",
        "All are struck by",
        "justness of his views but no one",
        "to carry them out so he takes a",
        "a divsion--stipulates that no one",
        "interfere with his",
        "division to the decisive point and",
        "the victoy alone",
        "suggested another voice",
        "Andrew however did no answer that",
        "and went on dreaming of his triumphs",
        "the dispositions for hte nxt battle",
        "Nominally he is",
        "an adjutatnt on Kutuzovs staff but",
        "everything alone",
        "Kutuzov is removed",
        "he is appointed",
        "the other voice",
        "you are not ten times wounded",
        "betrayed well",
        "Prince Andrew answered",
        "I dont know what will happen and dont",
        "to know and cant but if i want",
        "glory want to be known to men",
        "be loved by them it is not my fault",
        "I want it and want nothing but that",
        "live only for that",
        "I shall never tell anyone but oh",
        "am I to do if I love nothing but",
        "and mens esteem Deaht wounds the",
        "of family--I fear nothing",
        "and dear as many persons are to",
        "sister wife--those dearest ot",
        "dreadful and unnatrual as it seems I",
        "give them all at once for a moment",
        "of triumph over men of love from",
        "I dont know and never shall know",
        "love of these men here he",
        "he listened to voices in the courtyard",
        "The voces were those of the orderlies",
        "were packing up one voice probably",
        "was teasing the old cook",
        "Prince Andrew knew and who was called Ti",
        "He was saying Ti I say Ti",
        "returned the old man",
        "a bit said the wag",
        "devil called out a voice drowned",
        "laughter of the orderlies and",
        "All the same I love and value",
        "but triumph over them all I Value",
        "The French had attacked that",
        "and seeing Kutuzov were ring at him",
        "After this volley the regimineal",
        "clutched at his leg several soldiers",
        "and a second lieutenant who was",
        "the flag let it fall from his hand",
        "and fell but caught on the",
        "of the nearst soliders",
        "ring withotu orders",
        "groaned Kutuzov despairingly and",
        "daround",
        "his voice trembling from a a",
        "of the feebleness of age",
        "he whispered pointing to the",
        "battalion and at the enemy",
        "that But before he had nished",
        "Prince Andrew feeling tears of",
        "and anger choking him had already",
        "from his horse and run to the flag",
        "Foward lads he shouted ina voice",
        "Here it is",
        "he seizing the staff of the flag and",
        "with pleasure the whistle of",
        "aimed at him",
        "hHurrah shouted Prince",
        "and scarcely able to hold up the",
        "flag he ran forward with full",
        "the whole battalion would follow him",
        "And really he only ran a few steps",
        "One solder moved and aonther and",
        "the whole battalion forward shouting",
        "and overtook him",
        "battalion ran up and took the flag",
        "was swaying from its weight in Prince",
        "hands but he was immediately",
        "Prince aAndrew again seized the",
        "dragging it by teh staff ran on",
        "In front he saw our",
        "some of whome were ghting",
        "having abandoned their guns",
        "He also saw",
        "soldiers who were seizing the",
        "horses and turning the guns round",
        "Prince Andrew and the battlalion were",
        "within twnty paces of the cannon",
        "HE heard the whistle of bullets abnove",
        "and to the right and left",
        "soldiers continually groaned an d",
        "But he did not look at them he",
        "only at what was going on in front",
        "He now saw",
        "gure of ared-haired gunner with his",
        "knocked awry pulling one end of a",
        "a a French soldier tugged at the",
        "He could distinctly see the",
        "yet angry expression on the faces of",
        "two men who evidently did not",
        "what they were doing",
        "thoguth Prinece Andrew as he",
        "Why doesnt the",
        "run away as he is unarmed Why",
        "the Frenchman stab him He will",
        "away before the Frenchman rememebrs",
        "bayonet and stabs him",
        "another soldier trailing his",
        "ran up to the struggling men and the",
        "of the red-haired gunner who had",
        "secured the mop and still did",
        "what awaitred him was about",
        "But Prince Andrew did not",
        "IT seemed to him as",
        "one of the soliders near him hit him",
        "head with the full swing of a",
        "It hurt a little but the worst of",
        "the pain distracted him and",
        "seeing what he had been looking at",
        "Whats this Am I falling My legs",
        "way thought he and fell on",
        "He opened his eyes hoping to",
        "the struggle of the Frenchmen with",
        "whether the",
        "had been killed or not and",
        "cannon had been captured or saved",
        "But he saw nothing",
        "nothing but the sky--the lofty sky",
        "clear yet still immeasurably lofty",
        "clouds gliding slowly acorss it",
        "How quiet peaceful and solmen not at",
        "as I ran thought Prince",
        "as we ran shouting and ghting not at",
        "as the gunner and the Frenchman with",
        "frightened and angry faces struggled",
        "mop how differently do those",
        "across that lofty innite sky How",
        "it I did not see that lofty sky",
        "And how happy I am to have found it at",
        "Yes All is vanity all falsehood",
        "There is nothing",
        "But even it does not",
        "In the rearguard Dokhturov and",
        "rallying some battalions kept up",
        "re at the French cavalry that",
        "IT was growing",
        "On the narrow Augusd Dam where for",
        "years the old miller had been",
        "to sit on his tasselled cap",
        "angling while his grandson with",
        "rolled up handled the",
        "sh in the watering can on that",
        "over which for so many years Moravians",
        "shaggy caps and blue jackets had",
        "driver their two-horse carts loaded",
        "wheat and had returned dusty with",
        "their carts--on that narrow",
        "the wagons and the cannon under",
        "hoofs and between the wagon",
        "men disgured by fear of death now",
        "togther crushing one another dying",
        "over the dying and killing one",
        "only to move on a few steps and be",
        "themselves in the same way",
        "seconds acannonball flew compressing",
        "air around or a shell burst in the",
        "of that dense throng killing some",
        "with blood those near them",
        "On the Pratzen Heights where",
        "fallen with the flagstaff in his",
        "lay Prince Andrew Bolkonsky bleeding",
        "and unconsciously uttering a",
        "piteous and childlike moan",
        "he ceased moaning and became quite",
        "He did not know how long his",
        "Suddenly he again",
        "that he was alive and suffering from a",
        "lacerating pain in his head",
        "is it that lofty sky that I did",
        "till now but saw today was his",
        "And I did not know this",
        "either he thought",
        "not know anything anything at all",
        "But where am I He listened and",
        "the sound of approaching horses",
        "He opened his",
        "Above him aain was the same lofty",
        "clouds that had risen and were",
        "still higher and between them",
        "He did not turn his head",
        "did not see those wh judging by the",
        "of hoofs and voices had ridden up",
        "It was Napoleon",
        "by two aides-de-camp",
        "over the battleeld had given nal",
        "to streng the batteries ring at the",
        "Augesd Dam and was looking at the",
        "wounded left on the eld",
        "Thats a ne death said",
        "he gazed at Bolkonski",
        "that this was said of him",
        "it was Napoleon who said it",
        "the speaker addressed as Sire",
        "the words as he might have heard",
        "Not only did they",
        "him but he took no notice of",
        "and at once forgot them",
        "he felt himself blleding ot",
        "and he saw above him the remote",
        "He knew it was",
        "hero--but at that moment",
        "seemed to him such a small",
        "comparedw ith what was passing",
        "between himself and that lofty innite",
        "with the clouds flying over it",
        "moment it meant nothing to him who",
        "be standing over him or what was said",
        "him he was only glad that people were",
        "near him and only wished that",
        "help him and bring him back to",
        "which seemed to him so beautiful now",
        "he had today learned to understand it",
        "He collected all his",
        "to stir and utter a sound",
        "moved his legs and uttered a weak",
        "groan which aroused his own pity",
        "He is alive said Napoleon",
        "young man up and carry him to the",
        "Having said this",
        "rode on to meet Marshal Lannes who",
        "in hand rode up smiling to the",
        "Prince Andrew rememebred nothing",
        "he lost consciousness from the",
        "pain of being lifted onto the",
        "jolting while being moved and the",
        "of his wound at the dressing",
        "He did not regain consciousness till",
        "in the day when with other wounded",
        "captured Russian ofcers he was carried",
        "During this transfer",
        "a little stronger and was able to",
        "about him and even speak",
        "he heard on coming to his senses were",
        "of aFrench convoy ofcer who said",
        "We must halt here the Emperor",
        "here immediately it will please",
        "see these gentlemen prisoners",
        "Bonaparte having come up",
        "gallop stopped his horse",
        "senior he asked on seeing the",
        "They d the colonel Prince",
        "You are the commander of the",
        "Alexanders regiment of Horse",
        "I commanded a",
        "Your regiment",
        "its duty honourably said Napoloen",
        "The praise of a great commander is",
        "highest reward said Repnin",
        "I bestow it with pleasure said",
        "And how is that young man",
        "Prince Repnin d Lieutenant",
        "After looking at him Napoleon smiled",
        "Hes very young to come to meddle",
        "Youth is no hindrance to",
        "muttered Sukhtelen in a failing",
        "A splendid reply said Napoleon",
        "Young man you will go far",
        "Andrew who had also been brought",
        "the Emperors eyes to complete",
        "of prisoners could not fail to",
        "Napoleon apparently",
        "seeing him on the battleeld",
        "him again used the epithet",
        "man that was connected in his",
        "with Prince Andrew",
        "man said he",
        "brave Thought ve minutes before",
        "Andrew had been able to say a few",
        "to the soldiers who were carrying",
        "with his eyes xed straight on",
        "he was silent",
        "that moment seemed to him all the",
        "that engrossed Napoleon so mean",
        "hero himself with his paltry vanity",
        "joy in victory appear compared to the",
        "equitable and kindly sky which he",
        "seen and understood that he could",
        "Everything seemed so",
        "insignicant in comparison with teh",
        "and solemn train of thought that",
        "from loss of blood suffering and",
        "of death aroused in him",
        "into Napoleons eyes Prince Andrew",
        "of the insignicance of greatness and",
        "unimportance of life which no one",
        "and the still greater",
        "of death the meaning of which no",
        "alive could understand or explain",
        "Emperor without waiting for an answer",
        "away and said to one of the ofcers",
        "went Have these gentlmen attneded",
        "taken to my bivouc let my doctor",
        "examine their wounds",
        "Repnin and he spurred his horse",
        "The soldiers who had carried",
        "Andrew had noticed and taken the little",
        "icon Princess Mary had hung round",
        "neck but seeing the favour",
        "Emperor showed the prisoners they now",
        "to reutn the holy image",
        "Andrew did not see how and by whom it",
        "but the little icon with its",
        "gold chain suddenly appeared upon his",
        "outside his uniform",
        "thought Prince Andrew glancing",
        "icfon his sister had hung round his",
        "with such emotion and reverence it",
        "be good if everything were as clear",
        "simple as it seems to Mary",
        "would be to know where to seek for",
        "this life and what to expect after",
        "the grave How happy and calm I",
        "be if I could now say Lord have",
        "on me",
        "I say that Either to a Power undenable",
        "which I not only cannot",
        "but which I Cannot even express",
        "Great All or Nothing--said",
        "himself or to that God who has",
        "into this amulet by Mary There",
        "certain nothing at all except",
        "of everything I",
        "the greatness of something",
        "but all-important",
        "At every jolt he again",
        "pain his feverishness",
        "and he grew dlierious",
        "father wife sister and future son",
        "the tenderness he had felt the night",
        "the battle the gure of the",
        "little Napoleon and above all this",
        "sky formed the chief subjects of",
        "delirious fancies",
        "peaceful happines of Bald Hills",
        "He was already",
        "that happiness when that little",
        "had suddenly appeared with his",
        "look of shortsighted delight at",
        "of others and doubts and",
        "followed and only the heavens",
        "Toward morning all these",
        "melted and merged into the chaos and",
        "of unconsciousness and obligivion",
        "in the opinion of Napoleons doctor",
        "was much more likely to end in",
        "than in convalescence",
        "bilious subject said Larrey",
        "And Prince",
        "others fatally wounded was left to",
        "We are not the same",
        "glory is terror",
        "Its not that serious",
        "Rolly Louis Gucci Fendi Prada",
        "Me and Marc fucking Rutzuo",
        "My night is deception",
        "I count 6 shots",
        "The devil is all around me",
        "Style and Substance",
        "Are miracles meant for us",
        "Accept Everything",
        "And now something else",
        "Shut up and vibe",
        "Night Addict",
        "Losing my Religion",
        "Life is spent in Skinner Boxes",
        "I am Slayer",
        "Take me to your Skinner Box",
        "Life inside a celluloid dream",
        "Play till your out of moves",
        "This rhythm resembles home",
        "Bad Things Happen",
        "Acts of Rebellion",
        "Lenins on Sale Again",
        "South of Heaven",
        "To live means dying",
        "We Were Bored by the 2nd Bomb",
        "Kiss Kiss Bang Bang",
        "Some like it hot",
        "The Wolf Waits",
        "Move Mojito",
        "Man is Shockingly Predictable",
        "I am no one",
        "Are you the devil",
        "Shut up dude",
        "Its Britney Bitch",
        "Au revoir",
        "Once Upon a Time in Paris",
        "The sin of man",
        "Do not negotiate with thosn",
        "East of Eden",
        "Love is Eastside",
        "City never sleeps",
        "Waterfalls-dont go chasing them",
        "Order tends to disorder",
        "Waiting for the pendulum",
        "Reject Modernity",
        "Divorce yourself from society",
        "Everythings cool when were all",
        "for the throneEverythings happy",
        "were all smiling out of",
        "Only wolf left alive",
        "Thanks to the Lord in advance",
        "Reals Gs move in silence",
        "Are we having fun yet",
        "Dont take advice",
        "No Happy Endings",
        "If only it were all so simple",
        "Sinister Lone Rider",
        "Forth And fear no darkness",
        "The drugs keep on calling",
        "Now what",
        "what happened",
        "Waiting for the world to end",
        "We came We saw We left",
        "The End of the Fucking World",
        "sorry",
        "Well folks thats it",
        "Excuse me for living",
        "Wishing for the apocalypse",
        "Bring on the apocalpyse",
        "Welcome to Me",
        "Your moms garage",
        "ur mom",
        "Members Only",
        "Lake Shore Drive",
        "Halfway to Hating Myself",
        "Stop Thinking",
        "Alice in the Wall",
        "Let My Pipe Bang",
        "I want a daughter while Im still",
        "I wanna hold her hand--show her",
        "before the damage is done",
        "Investiage 311",
        "The Trees are Plastic",
        "We Killed Art",
        "On again off again soulmate",
        "Thanks Kanye very cool",
        "Everybody asks What are you",
        "Take this shit to school",
        "Jesus is Quiet Here",
        "Sharkeisha No",
        "Lifes a bitch  you die",
        "Me myself and I",
        "I wish I knew how to quit you",
        "Trade your pawn",
        "Im viral as fuck",
        "Trevor Reznik Does Not Exist",
        "Whats up its Robert Boujay AKA",
        "Pretty much GG",
        "Nobody Asked",
        "Didnt Ask",
        "Didnt Ask Dont Care",
        "Cope Dealer",
        "Pass the asparagus",
        "Someone already does",
        "Man is a wolf to man",
        "The warden makes house calls",
        "Well always have Paris",
        "Shes a monster",
        "You have half my attention",
        "What if no one believes you",
        "youre still here",
        "Big mistake huge",
        "Its because of mans nature that",
        "and sacrice are two sides of the"
    ]

    if not index:

        import random
        index = random.randint(0, len(quotes))

    if index > len(quotes) - 1:
        split_index = 1
        if index > 2*len(quotes) - 2:
            split_index = 2
        if index > 3*len(quotes) - 3:
            split_index = 3
        if index > 4*len(quotes) - 4:
            split_index = 4
        if index > 5*len(quotes) - 5:
            split_index = 5
        if index > 6*len(quotes) - 6:
            split_index = 6
        if index > 7*len(quotes) - 7:
            return str(index)

        truncated_index = int(
            index % len(quotes)
        )
        try: 
            ret = quotes[truncated_index].split(" ")
            ret = " ".join(
                ret[split_index:]
            )
            if len(ret) < 6:
                return str(index)
        except:
            return str(index)
    else:
        ret = quotes[index]

    ret = ret.replace("&", "and").replace("|", "-").replace("?", "").replace('"',"")
    return ret
